/*
 * TestPlan microservice
 * TestPlan microservice api documentation
 *
 * The version of the OpenAPI document: v1
 * Contact: service.testplan@xq.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.xq.testplan.api.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Response
 */
class ResponseTest {
    private final Response model = new Response();

    /**
     * Model tests for Response
     */
    @Test
    void testResponse() {
        // TODO: test Response
    }

    /**
     * Test the property 'statusCode'
     */
    @Test
    void statusCodeTest() {
        // TODO: test statusCode
    }

    /**
     * Test the property 'statusMsg'
     */
    @Test
    void statusMsgTest() {
        // TODO: test statusMsg
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    void uuidTest() {
        // TODO: test uuid
    }

}
